DROP PROCEDURE IF EXISTS UPDATEDATETIME;

CREATE PROCEDURE UPDATEDATETIME(
	IN SERVICE_DATE DATE,
	IN SERVICE_WEEK VARCHAR(50),
	IN SERVICE_YEAR INT,
	IN SERVICE_YEARMONTH DATE,
	IN SERVICE_QUARTER INT
) BEGIN
INSERT INTO
	datetime_dimension
VALUES
	(
		service_date,
		service_week,
		service_year,
		service_yearmonth,
		service_quarter
	);
END