DROP PROCEDURE IF EXISTS UPDATEJOBPOST;

CREATE PROCEDURE UPDATEJOBPOST(
	IN JOBPOSTINGID VARCHAR(30),
	IN COMPANYID VARCHAR(30),
	IN JOBTITLE VARCHAR(100),
	IN WORKREMOTEALLOWED BIT,
	IN JOBLOCATION VARCHAR(50),
	IN JOBDESC VARCHAR (10000),
	IN APPLYLINK VARCHAR(100),
	IN JOBSTATE BIT,
	IN OPENDATE DATE,
	IN CLOSEDATE DATE
) BEGIN
INSERT
	IGNORE INTO jobPost_facts
VALUES
	(
		JOBPOSTINGID,
		COMPANYID,
		JOBTITLE,
		WORKREMOTEALLOWED,
		JOBLOCATION,
		JOBDESC,
		APPLYLINK,
		JOBSTATE,
		OPENDATE,
		CLOSEDATE
	);

END