DROP PROCEDURE IF EXISTS UPDATEJOBPOST;
CREATE PROCEDURE UPDATEJOBPOST(
	IN JOBPOSTINGID INT,
	IN COMPANYID INT,
	IN JOBTITLE VARCHAR (20),
	IN EXPLEVEL VARCHAR(20),
	IN WORKREMOTEALLOWED BIT,
	IN JOBLOCATION VARCHAR (50),
	IN REQUIREMENT VARCHAR(100),
	IN APPLYLINK VARCHAR(100),
	IN JOBSTATE BIT,
	IN OPENDATE DATE,
	IN CLOSEDATE DATE
) BEGIN
INSERT INTO
	jobPost_facts
VALUES
	(
		JOBPOSTINGID,
		COMPANYID,
		EXPLEVEL,
		WORKREMOTEALLOWED,
		JOBLOCATION,
		REQUIREMENT,
		APPLYLINK,
		JOBSTATE,
		OPENDATE,
		CLOSEDATE
	);
END