DROP PROCEDURE IF EXISTS UPDATECOMPANY;
CREATE PROCEDURE UPDATECOMPANY(
	IN COMPANYID INT,
	IN CNAME VARCHAR(20), 
	IN CHQLOCATION VARCHAR(50),
	IN CWEBSITE VARCHAR(100),
	IN CFIELD VARCHAR(50)
) BEGIN
INSERT INTO
	company_dimension
VALUES
	(
		COMPANYID,
		CNAME,
		CHQLOCATION,
		CWEBSITE,
		CFIELD
	);
END