-- Active: 1687149754613@@127.0.0.1@3306@LinkedInDB
DROP PROCEDURE IF EXISTS UPDATECOMPANY;

CREATE PROCEDURE UPDATECOMPANY(
	IN COMPANYID VARCHAR(30),
	IN CNAME VARCHAR(100),
	IN CHQADDRESS VARCHAR(50),
	IN CHQZIPCODE INT,
	IN CURL VARCHAR(100),
	IN CFIELD VARCHAR(50)
) BEGIN
INSERT
	IGNORE INTO company_dimension
VALUES
	(
		COMPANYID,
		CNAME,
		CHQADDRESS,
		CHQZIPCODE,
		CURL,
		CFIELD
	);

END